### ISSUE TITLE
Reuse is relevant

### ISSUE THREAD

**Issue by heades** [dorchard/granule#11]
The following type checks -- using old syntax:

```
f : |Int| 2 -> Int
f |x| = x
```

In fact, if we have a type `|a| c`, then an input of type `|a|` can be use **at most** `n` times, and not exactly `n` times.

For example, all of the following work:

```
f : |Int| 3 -> Int
f |x| = x + x + x
```

```
f : |Int| 3 -> Int
f |x| = x + x
```

```
f : |Int| 3 -> Int
f |x| = x
```

```
f : |Int| 3 -> Int
f |x| = 1
```

**Comment by dorchard** [comment]
Yes you're right, but that was on purpose. It seemed to me that was the most useful thing for actual programming (that involves branching). If you want exact bounds then you can write:
```
f : |Int| 3= -> Int
f |x| = x + x + x
```
(there is a coeffect type of exact naturals).

**Comment by dorchard** [comment]
(could probably have a better syntax for this though like:
```
f : Int |3 : Nat=| -> Int
f |x| = x + x + x
```
also using the new syntax style)

**Comment by vimuel** [comment]
From my (limited) understanding the expected behaviour for linear types is like @heades points out (see [Substructural type system on Wikipedia](https://en.wikipedia.org/wiki/Substructural_type_system)).

`3=` seems a bit idiosyncratic to me.

Also, if I recall correctly Idris uses `Fin 3` for a finitely bounded `Nat` (I think excluding the upper bound). Couldn't we use something like this?

**Comment by heades** [comment]
@dorchard Thanks, and if that's what we want, then I am fine with it.  I was demoing the language to my PL Concepts class, and noticed what I reported above.  In the TLLA abstract I noticed that you say "exactly" in there, and I didn't notice the special syntax.

From a perspective of structural rules it makes sense, because the reuse coeffect simply restricts the of-course modality, and hence, has both weakening and contraction.

**Comment by dorchard** [comment]
Whoops, saying "exactly" was a mistake (I think that was the old thinking but at sometime I decided it would work better to allow "at most"). The special syntax for equality on naturals (giving "exact" is  new as of mid-ICFP. I think it could be tweaked a bit more to allow `Nat` to be implicitly converted to `Nat=`. I agree `3=` is a bit odd, so perhaps `3 : Nat =` would work better?

**Comment by dorchard** [comment]
re @vimuel, at the moment `3` essentially means `Fin 3`.

**Comment by heades** [comment]
@dorchard That's fine, and I think having it be "at most" is good, just wanted to make sure I understand the details.  We will have to make sure our formal specification makes that change.  I am actually starting on that today.
