### ISSUE TITLE
Add support for negative type signatures

### ISSUE THREAD

**Issue by vimuel** [dorchard/granule#12]
As we discussed in the pub earlier this week, consider adding support for anti-type signatures that gram asserts to be untypeable, e.g.

```agda
dub / |Int| 3= -> Int
dub : |Int| 2= -> Int
dub |x| = x + x
```
would pass, while
```agda
dub / |Int| 3 -> Int
dub : |Int| 2= -> Int
dub |x| = x + x
```
would fail, because assuming that 3 is a max bound, `dub : |Int| 3 → Int` would be a valid type.

`/` is some character TBD that means "not of type".

The motivation for this is mainly machine checked documentation.

**Comment by vimuel** [comment]
More thoughts on our favourite topic—syntax:

Could use `~`, which reminds me of logical not.
```agda
dub ~ |Int| 3= -> Int
dub : |Int| 2= -> Int
dub |x| = x + x
```
Could use `%`, which could be thought of as the struck-through version of `:`.
```agda
dub % |Int| 3= -> Int
dub : |Int| 2= -> Int
dub |x| = x + x
```
Nicest is maybe `÷`, which looks more like a struck-through `:`, but with the disadvantage that some people may find it cumbersome to type and it's not ASCII.
```agda
dub ÷ |Int| 3= -> Int
dub : |Int| 2= -> Int
dub |x| = x + x
```

**Comment by vimuel** [comment]
PS: maybe "untype signature" is a better term? To me "anti" evokes a sense of dual (or exactly two opposites), while "untype signature" makes it clearer that it is simply *a* type that doesn't hold.

**Comment by vimuel** [comment]
PPS: maybe not such a good idea after all, considering that "untype" is probably misleadingly close to "untyped".

Hmm... maybe...

good type signature → consistent, typechecks
bad type signature → inconsistent, fails to typecheck
ugly type signature → inconsistent, typechecks

?

Or I'm just being too cynical again.

**Comment by heades** [comment]
What are these for?  Is there a technical need for them, or just as documentation for the programmer?

**Comment by vimuel** [comment]
They would basically be a nice gimmick to have. It would make it very straightforward for us to make integration tests more robust, by including edge cases that should not typecheck.

In my example
```
dub / Int |3=| -> Int
dub : Int |2=| -> Int
dub |x| = x + x
```
this documents that `dub` should never typecheck with a reuse bound of exactly 3. If `dub : Int |3=| → Int` suddenly typechecks, then we know that we probably broke something somewhere.

Maybe it could also be useful to check and document that a type polymorphic function can't possibly take a particular concrete type? Not sure if that makes sense.

**Comment by vimuel** [comment]
Also—unless I am misunderstanding something—the implementation of this feature should be quite straightforward. If @dorchard agrees, I would have a stab at this.

**Comment by heades** [comment]
Thanks for clarifying, @vimuel.

It makes sense, and your point about polymorphism is something I thought about too.  For constrained polymorphism this could be a nice feature.

**Comment by vimuel** [comment]
Just jotting down some ideas that have popped into my head, at the risk of posting complete nonsense here:

We may not want to write the exact atomic-level effect type for our program and instead resort to effect classes (#50), e.g. `foo : FileIO ()`, but at the same time we would like to ensure that `foo` doesn't overwrite any existing files.

Perhaps negative type specifications could give us a way of asserting that `foo` never enters a certain state which is a subtype of `FileIO`. In a way this might relate to computation tree logic, but I'm not sure.

See also _branching of effects_ on our [project page](https://github.com/dorchard/granule/projects).

**Comment by vimuel** [comment]
Moved to a discussion platform as not relevant to the current implementation.
