### ISSUE TITLE
Gram is already taken as a name?

### ISSUE THREAD

**Issue by vimuel** [dorchard/granule#13]
[GitHub Repo](https://github.com/gramlang/gram)
[Paper](https://s3.amazonaws.com/stephan-misc/paper/latest.pdf)

Do we need to do anything about this?

**Comment by heades** [comment]
Nice find @vimuel.  We might need to change the name, but it's @dorchard's call.  As we extend and expand our language we might want it to stand out more when people are trying to search for it.

**Comment by dorchard** [comment]
Oh dear. That is a bit depressing. I will have a ponder what to do. Gram is sort of a perfect name for us....

**Comment by heades** [comment]
I have a name in my pocket I was using for another language, but I am happy to change it to something else, and donate to the cause. :-)

Gram is good, because it relates to what the language is all about, but how about "Grady".  It has a good ring to it, and fits well like Gram does.

Googling "Grady Programming Language" does not come up with much either.

**Comment by vimuel** [comment]
So, we've been brainstorming, and this should be a comprehensive list of candidates:

- Grady
- Grain
- Grammo
- Granule
- Gray
- Gru
- Gry

I came up with a nice logo for Gray:
<img width="230" alt="gray" src="https://user-images.githubusercontent.com/17603372/30616083-f3f78cdc-9d88-11e7-895f-25bebd992fc7.png">

With Gru, we would get the logo + glory from Despicable Me:
<img width="250" alt="gru" src="https://i.pinimg.com/originals/04/d7/f2/04d7f2a6c6685bcd52cd59d5518082ec.png">

**Comment by heades** [comment]
My personal favorites are:

Grady

Granule

Gray - Love the logo.

Gru reminds me too much of Guru which was a PL developed by Aaron Stump at UIowa.

**Comment by vimuel** [comment]
@heades So I spoke to @dorchard this morning and we both seem to converge on *Granule* for the language and `gran` for the executable to avoid typing too much at the command line.

Would you be happy to back that?

**Comment by heades** [comment]
Yep sounds good. I am happy with whatever you choose.
