### ISSUE TITLE
Approximation can lead to misunderstandings

### ISSUE THREAD

**Issue by vimuel** [dorchard/granule#19]
See [example](https://github.com/dorchard/granule/blob/master/examples/illtyped/gradingError.gr):

```idris
-- Should not be typeable:
foo : Int |2| -> Int |4|
foo |x| = |(x + x)|

-- Valid type signatures would be:
-- foo : Int |2| -> Int |1|
-- foo : Int |8| -> Int |4|
```

**Comment by dorchard** [comment]
Ah I figured this out- let's discuss later.

**Comment by dorchard** [comment]
These are actually valid typings, via something like the following derivation:

```
foo : Int |2| -> Int |4|
--------------------- (approximate output)
foo : Int |2| -> Int |0|
---------------------- (approximate input)
foo : Int |0| -> Int |0|
foo |x| = |(x + x)|
```
 Now this leads to a very misleading situation! One possible solution is to require explicit overapproximation on the result (as a term-level operation).

**Comment by dorchard** [comment]
I've changed things so that if you are doing promotion in a definition, no over approximation happens anymore. This has the nice result that 
```
-- Should not be typeable:
foo : Int |2| -> Int |4|
foo |x| = |(x + x)|
```
is not typable.
But instead the following is fine.
```
-- Should not be typeable:
foo : Int |8| -> Int |4|
foo |x| = |(x + x)|
```
