### ISSUE TITLE
Use Hpack to generate Cabal file

### ISSUE THREAD

**Issue by vimuel** [dorchard/granule#22]
Our current Cabal file is a bit of a mess. As part of my endeavours to fix this, I decided to try out [Hpack](https://github.com/sol/hpack) to generate the Cabal file.

It's supported out of the box by Stack and seems to be viewed favourably by the [community](http://taylor.fausak.me/2017/04/12/better-haskell-packages-with-hpack/).

The result is on a [new branch](https://github.com/dorchard/granule/tree/hpack). It works like a charm—I used it to add support for machine-checked examples in the documentation via [doctest](https://github.com/sol/doctest/).

Here is a small [example](https://github.com/dorchard/granule/blob/hpack/app/Main.hs#L30-L33) from our codebase.

@dorchard Have a look and let me know what you think. I would be happy to merge this into master unless you have any objections.

**Comment by vimuel** [comment]
Plus check out this: https://github.com/dorchard/granule/tree/hpack#readme

Maybe too funky? 😮

**Comment by dorchard** [comment]
That looks good. I don't quite understand what is going on with the `app` example though? It seems to be a repeated of `Main.hs` with some comments. 

I like the ASCII art!

**Comment by vimuel** [comment]
Oh sorry, I moved `Main.hs` into a separate directory because that's what people do for some reason. I think it's to separate executables from the other code, which is then just a library.

It's probably not necessary. I can move it back.

**Comment by vimuel** [comment]
PS: I think if we want to put `granule` as a library onto hackage for example, we would be better off leaving the CLI separate.

**Comment by dorchard** [comment]
I'm not sure why we would want to export Granule as a library. Did you have a use case in mind?

**Comment by vimuel** [comment]
Yes, I do—for our test suite! Look at how much cleaner it is to just add `granule` as a dependency instead of listing all the individual files.

**Comment by vimuel** [comment]
2278ce05
