### ISSUE TITLE
intersectCtxts precedence

### ISSUE THREAD

**Issue by vimuel** [dorchard/granule#26]
### Failure in src/Context.hs:32: expression `intersectCtxts [("x", 1)] [("x", 2)]'
    expected: [("x", 1)]
    but got: [("x",2)]

**Comment by dorchard** [comment]
Great- yes this is good we are catching this. This was a bug that was introduced, and a bunch of stuff that it effected was changed, but the ordering here is really important. 

Fixed by c7c0946c9abf64d3bc7c8c95601d31cc9c16f672
