### ISSUE TITLE
Nonlinear use of linear variables is accepted

### ISSUE THREAD

**Issue by vimuel** [dorchard/granule#42]
```
go : Int |Hi| |Hi| -> Int |Hi|
go x = case x of ||x|| -> |(x * x * x)|
```

**Comment by dorchard** [comment]
This isn't a problem with Granule, but more a conceptual design choice baked in Granule: the security coeffect-tracked variables are completely non-linear. If we want to carefully mix bounded linearity and security levels we could do this... but I'm currently a little unsure of the best way to do this. How about the following alternative to the above:
```
go : Int |3=| |Hi| -> Int |Hi|
go |xb| = |(case xb of |x| -> (x * x * x))|
```
If we wanted a linear security variables, we could do this by adapting the algebra, which at the moment allows arbitrary contraction taking the join of security levels.

Should I close this issue? We probably want to make a not of this question though somewhere.

**Comment by vimuel** [comment]
Thanks for clarifying, @dorchard. At the moment it is a question of documentation then.
