### ISSUE TITLE
Case does unboxing and matching should count as a usage

### ISSUE THREAD

**Issue by dorchard** [dorchard/granule#56]
The following is allowed, but I think it is unsound:
```
import Bool

foo : Bool |0| -> Bool
foo x =
  case x of
    |False| -> False;
    |True| -> True
```
This is because we are not counting the pattern match as a usage, which it actually is.
This program should be equivalent to the following which is of course ill-typed:
```
fooA : Bool |0| -> Bool
fooA |x| =
  case x of
    False -> False;
    True -> True
```
I think what we need is for the pattern matching to actually modify the type of the guard here.

**Comment by vimuel** [comment]
Isn't this because data constructors are nonlinear? I was actually going to ask you about this because when looking at the linearity lattice today I wondered why the pair constructor is just assumed to be cartesian.

Is this is what you meant?
