### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by vimuel** [dorchard/granule#7]
Should add some tests. Let's confer next Wednesday, @dorchard?

**Comment by dorchard** [comment]
(hah, I just sent you an e-mail about this). Let's.

**Comment by vimuel** [comment]
Haha great minds think alike. (Or as we say in German: "Two idiots, one thought.") 👍

I have assigned myself to this.

**Comment by dorchard** [comment]
Okay- I've added some stubs and started some `Arbitrary` instances. I think we also want to use the example files as test fixtures and get them to be automatically checked (i.e., they should parse and type check)- which is how I use them at the moment.

**Comment by vimuel** [comment]
Examples now get type checked as part of the test suite.

**Comment by dorchard** [comment]
Excellent.

**Comment by vimuel** [comment]
We need more tests, but the first step was checking whether the examples type check, so I will close this for now.
