### ISSUE TITLE
Multiple multi-line comments leads to parts of a file going missing

### ISSUE THREAD

**Issue by dorchard** [dorchard/granule#72]
MWE:
```
{- First line comment needs to be here -}

bad : Int
bad = |1|

{- Break -}

ok : Int
ok = 1
```

This type checks. If you look at the debugger, what is happening is that the first (bad) definition is not even being parsed. Instead the AST contains just the second (fine) definition.

**Comment by vimuel** [comment]
Quick fix during my break from my Haskell day job :)
